dist: bionic
language: generic
before_install:
- |
  echo "Checking if a CI run is needed post commit: ${TRAVIS_COMMIT_RANGE}"
  if ! git diff --name-only ${TRAVIS_COMMIT_RANGE} | grep -qvE '(\.png$)|(\.pdf$)|(\.html$)|^(LICENSE)'
  then
    echo "Only doc files were updated, not running the CI."
    exit
  fi
- sudo add-apt-repository --yes ppa:js-reynaud/kicad-5.1
- sudo apt update -y
- sudo apt install --no-install-recommends -y kicad kicad-symbols kicad-templates
  kicad-footprints inkscape
script:
- cd scripts && ./pcb2svg.sh && cd ..
before_deploy:
- git config --local user.name "PCB Gerber Exporter"
- git config --local user.email "noreply@w4xzr.xyz"
- export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
- git tag $TRAVIS_TAG
- ls
- ls Gerbers/
deploy:
  provider: releases
  api_key:
    secure: HmMgQDWYSSYxs6tqQFAZA7MsmTChAdofTzczaTaBpCSBuTknxXcYnPZaK4aQMBbrK4E9inPn46Gh0UJ3YwPW4i/AT8XP/ROwVDGRgXbXYueQf6Su8yKReFYpep7etHLjgEoiQjKOfpctkYDsPeHNEuNFBvRNf5Sn94uCsipbBhZGiCU0d6bIdBhl9ThHn2V6KWWS1SIc35x3hJVZI95LLvtYYh1Goh6r7wKuISo2ps9RkOVBDJgIU/StHV9t5Iq+98Ezn78RXGfKF7IdA9AHrUNHkFciHM3+B51pbjyzRg2KjG6Z+p5eerGYg89jOznSR/hbvYJC08rqdgY5tLZWWB2i11MUzVAXKTQKr9YlT1xJRdmzzuIjMOVgAm3FGFj3VTaOZ72vjmNLzmpJx7wfPWDdQIH4kuZ2/vSD8LkYe8WNZKvoel+rbywtIfm0iVrf+MvQ4DMONQOxun4WaXkQbuLGG3mguTDqq7SYJj0XcDNanaU2F+DQ8LLRL4cahR2kJ4nBYtVN4tR3B53hT1XruiLt3+bGIfzTCrBpYdQgDFt1Y+sLH7ULFWpDffjiKQf0VxUoQE/123i0L6BdaP46QEMrc4Jd9Me/vDLV467HuByMWTesEUFAY0PbWFL5abKa6dnAochAWnBs4dfvpzZ3SjMWPzlQCbE4GeQHq7Z4wtM=
  file: Gerbers/PIN-102_gerbers.zip
  on:
    repo: w4xzr/PIN-102
  skip_cleanup: 'true'
